package org.practice.mybatis.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.yunyi.domain.LogResourcedownload;
import org.practice.mybatis.yunyi.domain.LogResourcedownloadExample;

public interface LogResourcedownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(LogResourcedownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(LogResourcedownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(LogResourcedownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(LogResourcedownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<LogResourcedownload> selectByExample(LogResourcedownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    LogResourcedownload selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") LogResourcedownload record, @Param("example") LogResourcedownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") LogResourcedownload record, @Param("example") LogResourcedownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(LogResourcedownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_ResourceDownload
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(LogResourcedownload record);
}