package org.practice.mybatis.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.yunyi.domain.Questionaires;
import org.practice.mybatis.yunyi.domain.QuestionairesExample;

public interface QuestionairesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(QuestionairesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(QuestionairesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(Questionaires record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(Questionaires record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Questionaires> selectByExampleWithBLOBs(QuestionairesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Questionaires> selectByExample(QuestionairesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    Questionaires selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Questionaires record, @Param("example") QuestionairesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Questionaires record, @Param("example") QuestionairesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Questionaires record, @Param("example") QuestionairesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(Questionaires record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Questionaires record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Questionaires
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Questionaires record);
}