package org.practice.mybatis.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.yunyi.domain.ReCustomerBusinesssystem;
import org.practice.mybatis.yunyi.domain.ReCustomerBusinesssystemExample;

public interface ReCustomerBusinesssystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(ReCustomerBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(ReCustomerBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(ReCustomerBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(ReCustomerBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<ReCustomerBusinesssystem> selectByExample(ReCustomerBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    ReCustomerBusinesssystem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReCustomerBusinesssystem record, @Param("example") ReCustomerBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") ReCustomerBusinesssystem record, @Param("example") ReCustomerBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(ReCustomerBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(ReCustomerBusinesssystem record);
}