package com.yoong.mybatis.accidence.northwind.domain;

import java.util.ArrayList;
import java.util.List;

public class EmployeeterritoriesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public EmployeeterritoriesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmployeeidIsNull() {
            addCriterion("EmployeeID is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeidIsNotNull() {
            addCriterion("EmployeeID is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeidEqualTo(Integer value) {
            addCriterion("EmployeeID =", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidNotEqualTo(Integer value) {
            addCriterion("EmployeeID <>", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidGreaterThan(Integer value) {
            addCriterion("EmployeeID >", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("EmployeeID >=", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidLessThan(Integer value) {
            addCriterion("EmployeeID <", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidLessThanOrEqualTo(Integer value) {
            addCriterion("EmployeeID <=", value, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidIn(List<Integer> values) {
            addCriterion("EmployeeID in", values, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidNotIn(List<Integer> values) {
            addCriterion("EmployeeID not in", values, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidBetween(Integer value1, Integer value2) {
            addCriterion("EmployeeID between", value1, value2, "employeeid");
            return (Criteria) this;
        }

        public Criteria andEmployeeidNotBetween(Integer value1, Integer value2) {
            addCriterion("EmployeeID not between", value1, value2, "employeeid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidIsNull() {
            addCriterion("TerritoryID is null");
            return (Criteria) this;
        }

        public Criteria andTerritoryidIsNotNull() {
            addCriterion("TerritoryID is not null");
            return (Criteria) this;
        }

        public Criteria andTerritoryidEqualTo(String value) {
            addCriterion("TerritoryID =", value, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidNotEqualTo(String value) {
            addCriterion("TerritoryID <>", value, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidGreaterThan(String value) {
            addCriterion("TerritoryID >", value, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidGreaterThanOrEqualTo(String value) {
            addCriterion("TerritoryID >=", value, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidLessThan(String value) {
            addCriterion("TerritoryID <", value, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidLessThanOrEqualTo(String value) {
            addCriterion("TerritoryID <=", value, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidLike(String value) {
            addCriterion("TerritoryID like", value, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidNotLike(String value) {
            addCriterion("TerritoryID not like", value, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidIn(List<String> values) {
            addCriterion("TerritoryID in", values, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidNotIn(List<String> values) {
            addCriterion("TerritoryID not in", values, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidBetween(String value1, String value2) {
            addCriterion("TerritoryID between", value1, value2, "territoryid");
            return (Criteria) this;
        }

        public Criteria andTerritoryidNotBetween(String value1, String value2) {
            addCriterion("TerritoryID not between", value1, value2, "territoryid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated do_not_delete_during_merge Sun Jun 03 14:25:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}