package com.yoong.mybatis.accidence.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yoong.mybatis.accidence.yunyi.domain.Requirement;
import com.yoong.mybatis.accidence.yunyi.domain.RequirementExample;
import com.yoong.mybatis.accidence.yunyi.domain.RequirementWithBLOBs;

public interface RequirementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(RequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(RequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(RequirementWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(RequirementWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<RequirementWithBLOBs> selectByExampleWithBLOBs(RequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Requirement> selectByExample(RequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    RequirementWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") RequirementWithBLOBs record, @Param("example") RequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") RequirementWithBLOBs record, @Param("example") RequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Requirement record, @Param("example") RequirementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(RequirementWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(RequirementWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Requirement
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Requirement record);
}