package com.yoong.mybatis.accidence.northwind.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yoong.mybatis.accidence.northwind.domain.Customerdemographics;
import com.yoong.mybatis.accidence.northwind.domain.CustomerdemographicsExample;

public interface CustomerdemographicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int countByExample(CustomerdemographicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int deleteByExample(CustomerdemographicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int deleteByPrimaryKey(String customertypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int insert(Customerdemographics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int insertSelective(Customerdemographics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    List<Customerdemographics> selectByExample(CustomerdemographicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    Customerdemographics selectByPrimaryKey(String customertypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") Customerdemographics record, @Param("example") CustomerdemographicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByExample(@Param("record") Customerdemographics record, @Param("example") CustomerdemographicsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByPrimaryKeySelective(Customerdemographics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerDemographics
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByPrimaryKey(Customerdemographics record);
}