package org.practice.mybatis.yunyi.domain;

public class Admintopages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AdminToPages.Id
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AdminToPages.AdminId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AdminToPages.PageId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private Integer pageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AdminToPages.ActionList
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String actionlist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AdminToPages.IsShow
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private Byte isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AdminToPages.IsDelete
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private Byte isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AdminToPages.Id
     *
     * @return the value of AdminToPages.Id
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AdminToPages.Id
     *
     * @param id the value for AdminToPages.Id
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AdminToPages.AdminId
     *
     * @return the value of AdminToPages.AdminId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AdminToPages.AdminId
     *
     * @param adminid the value for AdminToPages.AdminId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AdminToPages.PageId
     *
     * @return the value of AdminToPages.PageId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public Integer getPageid() {
        return pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AdminToPages.PageId
     *
     * @param pageid the value for AdminToPages.PageId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setPageid(Integer pageid) {
        this.pageid = pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AdminToPages.ActionList
     *
     * @return the value of AdminToPages.ActionList
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getActionlist() {
        return actionlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AdminToPages.ActionList
     *
     * @param actionlist the value for AdminToPages.ActionList
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setActionlist(String actionlist) {
        this.actionlist = actionlist == null ? null : actionlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AdminToPages.IsShow
     *
     * @return the value of AdminToPages.IsShow
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public Byte getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AdminToPages.IsShow
     *
     * @param isshow the value for AdminToPages.IsShow
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setIsshow(Byte isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AdminToPages.IsDelete
     *
     * @return the value of AdminToPages.IsDelete
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AdminToPages.IsDelete
     *
     * @param isdelete the value for AdminToPages.IsDelete
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }
}