package org.practice.mybatis.yunyi.domain;

import java.util.Date;

public class Requirement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.Id
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.RequirementNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String requirementno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.CustomerNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String customerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.CustomerName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.ContactName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String contactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.Phone
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.Email
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.BusinessSystemId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String businesssystemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.BusinessSystemNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String businesssystemno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.BusinessSystemMstSynNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String businesssystemmstsynno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.BusinessSystemName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String businesssystemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.ProductId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.CreateTime
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.Deadline
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.Answer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.Dealor
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String dealor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.DealTime
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String dealtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.Definition1
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String definition1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.Definition2
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String definition2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.DealResultName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String dealresultname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.promiseDate
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String promisedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.reqStatusName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String reqstatusname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.publishStatusName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String publishstatusname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.DeleteStatus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String deletestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.reqStatus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String reqstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.PublishStatus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String publishstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.PromiseVersion
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String promiseversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Requirement.FactVersion
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String factversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.Id
     *
     * @return the value of Requirement.Id
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.Id
     *
     * @param id the value for Requirement.Id
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.RequirementNo
     *
     * @return the value of Requirement.RequirementNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getRequirementno() {
        return requirementno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.RequirementNo
     *
     * @param requirementno the value for Requirement.RequirementNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setRequirementno(String requirementno) {
        this.requirementno = requirementno == null ? null : requirementno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.CustomerNo
     *
     * @return the value of Requirement.CustomerNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.CustomerNo
     *
     * @param customerno the value for Requirement.CustomerNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.CustomerName
     *
     * @return the value of Requirement.CustomerName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.CustomerName
     *
     * @param customername the value for Requirement.CustomerName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.ContactName
     *
     * @return the value of Requirement.ContactName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.ContactName
     *
     * @param contactname the value for Requirement.ContactName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.Phone
     *
     * @return the value of Requirement.Phone
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.Phone
     *
     * @param phone the value for Requirement.Phone
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.Email
     *
     * @return the value of Requirement.Email
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.Email
     *
     * @param email the value for Requirement.Email
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.BusinessSystemId
     *
     * @return the value of Requirement.BusinessSystemId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getBusinesssystemid() {
        return businesssystemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.BusinessSystemId
     *
     * @param businesssystemid the value for Requirement.BusinessSystemId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setBusinesssystemid(String businesssystemid) {
        this.businesssystemid = businesssystemid == null ? null : businesssystemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.BusinessSystemNo
     *
     * @return the value of Requirement.BusinessSystemNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getBusinesssystemno() {
        return businesssystemno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.BusinessSystemNo
     *
     * @param businesssystemno the value for Requirement.BusinessSystemNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setBusinesssystemno(String businesssystemno) {
        this.businesssystemno = businesssystemno == null ? null : businesssystemno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.BusinessSystemMstSynNo
     *
     * @return the value of Requirement.BusinessSystemMstSynNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getBusinesssystemmstsynno() {
        return businesssystemmstsynno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.BusinessSystemMstSynNo
     *
     * @param businesssystemmstsynno the value for Requirement.BusinessSystemMstSynNo
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setBusinesssystemmstsynno(String businesssystemmstsynno) {
        this.businesssystemmstsynno = businesssystemmstsynno == null ? null : businesssystemmstsynno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.BusinessSystemName
     *
     * @return the value of Requirement.BusinessSystemName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getBusinesssystemname() {
        return businesssystemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.BusinessSystemName
     *
     * @param businesssystemname the value for Requirement.BusinessSystemName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setBusinesssystemname(String businesssystemname) {
        this.businesssystemname = businesssystemname == null ? null : businesssystemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.ProductId
     *
     * @return the value of Requirement.ProductId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.ProductId
     *
     * @param productid the value for Requirement.ProductId
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.CreateTime
     *
     * @return the value of Requirement.CreateTime
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.CreateTime
     *
     * @param createtime the value for Requirement.CreateTime
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.Deadline
     *
     * @return the value of Requirement.Deadline
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.Deadline
     *
     * @param deadline the value for Requirement.Deadline
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setDeadline(String deadline) {
        this.deadline = deadline == null ? null : deadline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.Answer
     *
     * @return the value of Requirement.Answer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.Answer
     *
     * @param answer the value for Requirement.Answer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.Dealor
     *
     * @return the value of Requirement.Dealor
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getDealor() {
        return dealor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.Dealor
     *
     * @param dealor the value for Requirement.Dealor
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setDealor(String dealor) {
        this.dealor = dealor == null ? null : dealor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.DealTime
     *
     * @return the value of Requirement.DealTime
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getDealtime() {
        return dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.DealTime
     *
     * @param dealtime the value for Requirement.DealTime
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setDealtime(String dealtime) {
        this.dealtime = dealtime == null ? null : dealtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.Definition1
     *
     * @return the value of Requirement.Definition1
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getDefinition1() {
        return definition1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.Definition1
     *
     * @param definition1 the value for Requirement.Definition1
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setDefinition1(String definition1) {
        this.definition1 = definition1 == null ? null : definition1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.Definition2
     *
     * @return the value of Requirement.Definition2
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getDefinition2() {
        return definition2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.Definition2
     *
     * @param definition2 the value for Requirement.Definition2
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setDefinition2(String definition2) {
        this.definition2 = definition2 == null ? null : definition2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.DealResultName
     *
     * @return the value of Requirement.DealResultName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getDealresultname() {
        return dealresultname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.DealResultName
     *
     * @param dealresultname the value for Requirement.DealResultName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setDealresultname(String dealresultname) {
        this.dealresultname = dealresultname == null ? null : dealresultname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.promiseDate
     *
     * @return the value of Requirement.promiseDate
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getPromisedate() {
        return promisedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.promiseDate
     *
     * @param promisedate the value for Requirement.promiseDate
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setPromisedate(String promisedate) {
        this.promisedate = promisedate == null ? null : promisedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.reqStatusName
     *
     * @return the value of Requirement.reqStatusName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getReqstatusname() {
        return reqstatusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.reqStatusName
     *
     * @param reqstatusname the value for Requirement.reqStatusName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setReqstatusname(String reqstatusname) {
        this.reqstatusname = reqstatusname == null ? null : reqstatusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.publishStatusName
     *
     * @return the value of Requirement.publishStatusName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getPublishstatusname() {
        return publishstatusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.publishStatusName
     *
     * @param publishstatusname the value for Requirement.publishStatusName
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setPublishstatusname(String publishstatusname) {
        this.publishstatusname = publishstatusname == null ? null : publishstatusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.DeleteStatus
     *
     * @return the value of Requirement.DeleteStatus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getDeletestatus() {
        return deletestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.DeleteStatus
     *
     * @param deletestatus the value for Requirement.DeleteStatus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setDeletestatus(String deletestatus) {
        this.deletestatus = deletestatus == null ? null : deletestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.reqStatus
     *
     * @return the value of Requirement.reqStatus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getReqstatus() {
        return reqstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.reqStatus
     *
     * @param reqstatus the value for Requirement.reqStatus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setReqstatus(String reqstatus) {
        this.reqstatus = reqstatus == null ? null : reqstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.PublishStatus
     *
     * @return the value of Requirement.PublishStatus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getPublishstatus() {
        return publishstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.PublishStatus
     *
     * @param publishstatus the value for Requirement.PublishStatus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setPublishstatus(String publishstatus) {
        this.publishstatus = publishstatus == null ? null : publishstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.PromiseVersion
     *
     * @return the value of Requirement.PromiseVersion
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getPromiseversion() {
        return promiseversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.PromiseVersion
     *
     * @param promiseversion the value for Requirement.PromiseVersion
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setPromiseversion(String promiseversion) {
        this.promiseversion = promiseversion == null ? null : promiseversion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Requirement.FactVersion
     *
     * @return the value of Requirement.FactVersion
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getFactversion() {
        return factversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Requirement.FactVersion
     *
     * @param factversion the value for Requirement.FactVersion
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setFactversion(String factversion) {
        this.factversion = factversion == null ? null : factversion.trim();
    }
}