package com.yoong.mybatis.accidence.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yoong.mybatis.accidence.yunyi.domain.Authories;
import com.yoong.mybatis.accidence.yunyi.domain.AuthoriesExample;

public interface AuthoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(AuthoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(AuthoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(Authories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(Authories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Authories> selectByExample(AuthoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    Authories selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Authories record, @Param("example") AuthoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Authories record, @Param("example") AuthoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(Authories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Authories
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Authories record);
}