package com.yoong.mybatis.accidence.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yoong.mybatis.accidence.yunyi.domain.Customerevent;
import com.yoong.mybatis.accidence.yunyi.domain.CustomereventExample;
import com.yoong.mybatis.accidence.yunyi.domain.CustomereventWithBLOBs;

public interface CustomereventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(CustomereventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(CustomereventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(CustomereventWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(CustomereventWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<CustomereventWithBLOBs> selectByExampleWithBLOBs(CustomereventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Customerevent> selectByExample(CustomereventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    CustomereventWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") CustomereventWithBLOBs record, @Param("example") CustomereventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CustomereventWithBLOBs record, @Param("example") CustomereventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Customerevent record, @Param("example") CustomereventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(CustomereventWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CustomereventWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerEvent
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Customerevent record);
}