package com.yoong.mybatis.accidence.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yoong.mybatis.accidence.yunyi.domain.Onlineresource;
import com.yoong.mybatis.accidence.yunyi.domain.OnlineresourceExample;
import com.yoong.mybatis.accidence.yunyi.domain.OnlineresourceWithBLOBs;

public interface OnlineresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(OnlineresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(OnlineresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(OnlineresourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(OnlineresourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<OnlineresourceWithBLOBs> selectByExampleWithBLOBs(OnlineresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Onlineresource> selectByExample(OnlineresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    OnlineresourceWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") OnlineresourceWithBLOBs record, @Param("example") OnlineresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") OnlineresourceWithBLOBs record, @Param("example") OnlineresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Onlineresource record, @Param("example") OnlineresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(OnlineresourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(OnlineresourceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OnlineResource
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Onlineresource record);
}