package com.yoong.practice.mybatis.accidence.northwind.domain;

import java.math.BigDecimal;

public class OrderDetails extends OrderDetailsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order Details.UnitPrice
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private BigDecimal unitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order Details.Quantity
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private Short quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order Details.Discount
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private Float discount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order Details.UnitPrice
     *
     * @return the value of Order Details.UnitPrice
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public BigDecimal getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order Details.UnitPrice
     *
     * @param unitprice the value for Order Details.UnitPrice
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order Details.Quantity
     *
     * @return the value of Order Details.Quantity
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public Short getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order Details.Quantity
     *
     * @param quantity the value for Order Details.Quantity
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setQuantity(Short quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order Details.Discount
     *
     * @return the value of Order Details.Discount
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public Float getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order Details.Discount
     *
     * @param discount the value for Order Details.Discount
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setDiscount(Float discount) {
        this.discount = discount;
    }
}