package com.yoong.practice.mybatis.accidence.northwind.domain;

public class Shippers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shippers.ShipperID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private Integer shipperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shippers.CompanyName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Shippers.Phone
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shippers.ShipperID
     *
     * @return the value of Shippers.ShipperID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public Integer getShipperid() {
        return shipperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shippers.ShipperID
     *
     * @param shipperid the value for Shippers.ShipperID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setShipperid(Integer shipperid) {
        this.shipperid = shipperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shippers.CompanyName
     *
     * @return the value of Shippers.CompanyName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shippers.CompanyName
     *
     * @param companyname the value for Shippers.CompanyName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Shippers.Phone
     *
     * @return the value of Shippers.Phone
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Shippers.Phone
     *
     * @param phone the value for Shippers.Phone
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}