package com.yoong.practice.mybatis.accidence.northwind.domain;

public class Suppliers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.SupplierID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private Integer supplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.CompanyName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.ContactName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String contactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.ContactTitle
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String contacttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.Address
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.City
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.Region
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.PostalCode
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String postalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.Country
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.Phone
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.Fax
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Suppliers.HomePage
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String homepage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.SupplierID
     *
     * @return the value of Suppliers.SupplierID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public Integer getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.SupplierID
     *
     * @param supplierid the value for Suppliers.SupplierID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.CompanyName
     *
     * @return the value of Suppliers.CompanyName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.CompanyName
     *
     * @param companyname the value for Suppliers.CompanyName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.ContactName
     *
     * @return the value of Suppliers.ContactName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.ContactName
     *
     * @param contactname the value for Suppliers.ContactName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.ContactTitle
     *
     * @return the value of Suppliers.ContactTitle
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getContacttitle() {
        return contacttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.ContactTitle
     *
     * @param contacttitle the value for Suppliers.ContactTitle
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setContacttitle(String contacttitle) {
        this.contacttitle = contacttitle == null ? null : contacttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.Address
     *
     * @return the value of Suppliers.Address
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.Address
     *
     * @param address the value for Suppliers.Address
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.City
     *
     * @return the value of Suppliers.City
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.City
     *
     * @param city the value for Suppliers.City
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.Region
     *
     * @return the value of Suppliers.Region
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.Region
     *
     * @param region the value for Suppliers.Region
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.PostalCode
     *
     * @return the value of Suppliers.PostalCode
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.PostalCode
     *
     * @param postalcode the value for Suppliers.PostalCode
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.Country
     *
     * @return the value of Suppliers.Country
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.Country
     *
     * @param country the value for Suppliers.Country
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.Phone
     *
     * @return the value of Suppliers.Phone
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.Phone
     *
     * @param phone the value for Suppliers.Phone
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.Fax
     *
     * @return the value of Suppliers.Fax
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.Fax
     *
     * @param fax the value for Suppliers.Fax
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Suppliers.HomePage
     *
     * @return the value of Suppliers.HomePage
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Suppliers.HomePage
     *
     * @param homepage the value for Suppliers.HomePage
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage == null ? null : homepage.trim();
    }
}