package org.practice.mybatis.chap.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.chap.domain.Adminloginlogs;
import org.practice.mybatis.chap.domain.AdminloginlogsExample;

public interface AdminloginlogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(AdminloginlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(AdminloginlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(Integer adminloginlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(Adminloginlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(Adminloginlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Adminloginlogs> selectByExample(AdminloginlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    Adminloginlogs selectByPrimaryKey(Integer adminloginlogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Adminloginlogs record, @Param("example") AdminloginlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Adminloginlogs record, @Param("example") AdminloginlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(Adminloginlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminLoginLogs
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Adminloginlogs record);
}