package org.practice.mybatis.chap.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.chap.domain.ReNoticeBusinesssystem;
import org.practice.mybatis.chap.domain.ReNoticeBusinesssystemExample;

public interface ReNoticeBusinesssystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(ReNoticeBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(ReNoticeBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(ReNoticeBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(ReNoticeBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<ReNoticeBusinesssystem> selectByExample(ReNoticeBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    ReNoticeBusinesssystem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReNoticeBusinesssystem record, @Param("example") ReNoticeBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") ReNoticeBusinesssystem record, @Param("example") ReNoticeBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(ReNoticeBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_BusinessSystem
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(ReNoticeBusinesssystem record);
}