package org.practice.mybatis.chap.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.chap.domain.ReNoticeCustomer;
import org.practice.mybatis.chap.domain.ReNoticeCustomerExample;

public interface ReNoticeCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(ReNoticeCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(ReNoticeCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(ReNoticeCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(ReNoticeCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<ReNoticeCustomer> selectByExample(ReNoticeCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    ReNoticeCustomer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReNoticeCustomer record, @Param("example") ReNoticeCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") ReNoticeCustomer record, @Param("example") ReNoticeCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(ReNoticeCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Customer
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(ReNoticeCustomer record);
}