package org.practice.mybatis.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.yunyi.domain.Pagemenus;
import org.practice.mybatis.yunyi.domain.PagemenusExample;

public interface PagemenusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(PagemenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(PagemenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(Pagemenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(Pagemenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Pagemenus> selectByExample(PagemenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    Pagemenus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Pagemenus record, @Param("example") PagemenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Pagemenus record, @Param("example") PagemenusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(Pagemenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageMenus
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Pagemenus record);
}