package org.practice.mybatis.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.yunyi.domain.Pageactions;
import org.practice.mybatis.yunyi.domain.PageactionsExample;

public interface PageactionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(PageactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(PageactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(Pageactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(Pageactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Pageactions> selectByExample(PageactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    Pageactions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Pageactions record, @Param("example") PageactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Pageactions record, @Param("example") PageactionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(Pageactions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PageActions
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Pageactions record);
}