package org.practice.mybatis.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.yunyi.domain.Requirementinsertparams;
import org.practice.mybatis.yunyi.domain.RequirementinsertparamsExample;
import org.practice.mybatis.yunyi.domain.RequirementinsertparamsWithBLOBs;

public interface RequirementinsertparamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(RequirementinsertparamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(RequirementinsertparamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(RequirementinsertparamsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(RequirementinsertparamsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<RequirementinsertparamsWithBLOBs> selectByExampleWithBLOBs(RequirementinsertparamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Requirementinsertparams> selectByExample(RequirementinsertparamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    RequirementinsertparamsWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") RequirementinsertparamsWithBLOBs record, @Param("example") RequirementinsertparamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") RequirementinsertparamsWithBLOBs record, @Param("example") RequirementinsertparamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Requirementinsertparams record, @Param("example") RequirementinsertparamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(RequirementinsertparamsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(RequirementinsertparamsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RequirementInsertParams
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Requirementinsertparams record);
}