package org.practice.mybatis.yunyi.domain;

public class CustomereventWithBLOBs extends Customerevent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CustomerEvent.Description
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CustomerEvent.Solution
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String solution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CustomerEvent.Comment
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CustomerEvent.Description
     *
     * @return the value of CustomerEvent.Description
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CustomerEvent.Description
     *
     * @param description the value for CustomerEvent.Description
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CustomerEvent.Solution
     *
     * @return the value of CustomerEvent.Solution
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getSolution() {
        return solution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CustomerEvent.Solution
     *
     * @param solution the value for CustomerEvent.Solution
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setSolution(String solution) {
        this.solution = solution == null ? null : solution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CustomerEvent.Comment
     *
     * @return the value of CustomerEvent.Comment
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CustomerEvent.Comment
     *
     * @param comment the value for CustomerEvent.Comment
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}