package com.yoong.practice.mybatis.accidence.northwind.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yoong.practice.mybatis.accidence.northwind.domain.CustomercustomerdemoExample;
import com.yoong.practice.mybatis.accidence.northwind.domain.CustomercustomerdemoKey;

public interface CustomercustomerdemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerCustomerDemo
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int countByExample(CustomercustomerdemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerCustomerDemo
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int deleteByExample(CustomercustomerdemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerCustomerDemo
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int deleteByPrimaryKey(CustomercustomerdemoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerCustomerDemo
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int insert(CustomercustomerdemoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerCustomerDemo
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int insertSelective(CustomercustomerdemoKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerCustomerDemo
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    List<CustomercustomerdemoKey> selectByExample(CustomercustomerdemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerCustomerDemo
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") CustomercustomerdemoKey record, @Param("example") CustomercustomerdemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerCustomerDemo
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByExample(@Param("record") CustomercustomerdemoKey record, @Param("example") CustomercustomerdemoExample example);
}