package org.practice.mybatis.northwind.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.northwind.domain.EmployeeterritoriesExample;
import org.practice.mybatis.northwind.domain.EmployeeterritoriesKey;

public interface EmployeeterritoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int countByExample(EmployeeterritoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int deleteByExample(EmployeeterritoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int deleteByPrimaryKey(EmployeeterritoriesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int insert(EmployeeterritoriesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int insertSelective(EmployeeterritoriesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    List<EmployeeterritoriesKey> selectByExample(EmployeeterritoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") EmployeeterritoriesKey record, @Param("example") EmployeeterritoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EmployeeTerritories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByExample(@Param("record") EmployeeterritoriesKey record, @Param("example") EmployeeterritoriesExample example);
}