package org.practice.mybatis.northwind.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.northwind.domain.Shippers;
import org.practice.mybatis.northwind.domain.ShippersExample;

public interface ShippersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int countByExample(ShippersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int deleteByExample(ShippersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int deleteByPrimaryKey(Integer shipperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int insert(Shippers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int insertSelective(Shippers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    List<Shippers> selectByExample(ShippersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    Shippers selectByPrimaryKey(Integer shipperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") Shippers record, @Param("example") ShippersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByExample(@Param("record") Shippers record, @Param("example") ShippersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByPrimaryKeySelective(Shippers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Shippers
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByPrimaryKey(Shippers record);
}