package org.practice.mybatis.northwind.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.practice.mybatis.northwind.domain.Territories;
import org.practice.mybatis.northwind.domain.TerritoriesExample;

public interface TerritoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int countByExample(TerritoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int deleteByExample(TerritoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int deleteByPrimaryKey(String territoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int insert(Territories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int insertSelective(Territories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    List<Territories> selectByExample(TerritoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    Territories selectByPrimaryKey(String territoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") Territories record, @Param("example") TerritoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByExample(@Param("record") Territories record, @Param("example") TerritoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByPrimaryKeySelective(Territories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Territories
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    int updateByPrimaryKey(Territories record);
}