package org.practice.mybatis.northwind.domain;

public class Customers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.CustomerID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.CompanyName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String companyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.ContactName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String contactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.ContactTitle
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String contacttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.Address
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.City
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.Region
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.PostalCode
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String postalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.Country
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.Phone
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customers.Fax
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String fax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.CustomerID
     *
     * @return the value of Customers.CustomerID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.CustomerID
     *
     * @param customerid the value for Customers.CustomerID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.CompanyName
     *
     * @return the value of Customers.CompanyName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.CompanyName
     *
     * @param companyname the value for Customers.CompanyName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.ContactName
     *
     * @return the value of Customers.ContactName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.ContactName
     *
     * @param contactname the value for Customers.ContactName
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.ContactTitle
     *
     * @return the value of Customers.ContactTitle
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getContacttitle() {
        return contacttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.ContactTitle
     *
     * @param contacttitle the value for Customers.ContactTitle
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setContacttitle(String contacttitle) {
        this.contacttitle = contacttitle == null ? null : contacttitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.Address
     *
     * @return the value of Customers.Address
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.Address
     *
     * @param address the value for Customers.Address
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.City
     *
     * @return the value of Customers.City
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.City
     *
     * @param city the value for Customers.City
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.Region
     *
     * @return the value of Customers.Region
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.Region
     *
     * @param region the value for Customers.Region
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.PostalCode
     *
     * @return the value of Customers.PostalCode
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.PostalCode
     *
     * @param postalcode the value for Customers.PostalCode
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.Country
     *
     * @return the value of Customers.Country
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.Country
     *
     * @param country the value for Customers.Country
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.Phone
     *
     * @return the value of Customers.Phone
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.Phone
     *
     * @param phone the value for Customers.Phone
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customers.Fax
     *
     * @return the value of Customers.Fax
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customers.Fax
     *
     * @param fax the value for Customers.Fax
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }
}