package org.practice.mybatis.northwind.domain;

public class Customerdemographics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CustomerDemographics.CustomerTypeID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String customertypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CustomerDemographics.CustomerDesc
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    private String customerdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CustomerDemographics.CustomerTypeID
     *
     * @return the value of CustomerDemographics.CustomerTypeID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getCustomertypeid() {
        return customertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CustomerDemographics.CustomerTypeID
     *
     * @param customertypeid the value for CustomerDemographics.CustomerTypeID
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setCustomertypeid(String customertypeid) {
        this.customertypeid = customertypeid == null ? null : customertypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CustomerDemographics.CustomerDesc
     *
     * @return the value of CustomerDemographics.CustomerDesc
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public String getCustomerdesc() {
        return customerdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CustomerDemographics.CustomerDesc
     *
     * @param customerdesc the value for CustomerDemographics.CustomerDesc
     *
     * @mbggenerated Sun Jun 03 14:25:41 CST 2018
     */
    public void setCustomerdesc(String customerdesc) {
        this.customerdesc = customerdesc == null ? null : customerdesc.trim();
    }
}