package com.yoong.practice.mybatis.accidence.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yoong.practice.mybatis.accidence.yunyi.domain.Adminoperations;
import com.yoong.practice.mybatis.accidence.yunyi.domain.AdminoperationsExample;

public interface AdminoperationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(AdminoperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(AdminoperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(Adminoperations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(Adminoperations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Adminoperations> selectByExampleWithBLOBs(AdminoperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Adminoperations> selectByExample(AdminoperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    Adminoperations selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Adminoperations record, @Param("example") AdminoperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Adminoperations record, @Param("example") AdminoperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Adminoperations record, @Param("example") AdminoperationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(Adminoperations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Adminoperations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AdminOperations
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Adminoperations record);
}