package com.yoong.practice.mybatis.accidence.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yoong.practice.mybatis.accidence.yunyi.domain.Attachfile;
import com.yoong.practice.mybatis.accidence.yunyi.domain.AttachfileExample;

public interface AttachfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(AttachfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(AttachfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(Attachfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(Attachfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Attachfile> selectByExample(AttachfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    Attachfile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Attachfile record, @Param("example") AttachfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Attachfile record, @Param("example") AttachfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(Attachfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AttachFile
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Attachfile record);
}