package com.yoong.practice.mybatis.accidence.yunyi.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.yoong.practice.mybatis.accidence.yunyi.domain.Sort;
import com.yoong.practice.mybatis.accidence.yunyi.domain.SortExample;

public interface SortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int countByExample(SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByExample(SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insert(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int insertSelective(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    List<Sort> selectByExample(SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    Sort selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Sort record, @Param("example") SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByExample(@Param("record") Sort record, @Param("example") SortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKeySelective(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sort
     *
     * @mbggenerated Fri Dec 15 13:59:18 CST 2017
     */
    int updateByPrimaryKey(Sort record);
}